server:
  port: 9008
spring:
  application:
    name: itaobao-qa
  datasource:
    driver-class-namex: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.8.208:3306/itaobaob_qa?serverTimezone=UTC
    username: root
    password: 123456.sql
  jpa:
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 122.51.8.208
jwt:
  key: itaobao
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-adress: ture
feign:
  hystrix:
    enable: true