server:
  port: 9012
spring:
  application:
    name: itaobao-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.8.208:3306/itaobaob_user?serverTimezone=UTC
    username: root
    password: 123456.sql
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 122.51.8.208
  rabbitmq:
    host: 122.51.8.208
  security:
    user:
      name: admin
      password: 123456
      role: ADMIN
jwt:
  config:
    key: itaobao
    ttl: 36000000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-adress: ture